### ISSUE TITLE
ssd1306_ic2 demo shows only 8 rows

### ISSUE THREAD

**Issue by rolanddemeester** [codewitch-honey-crisis/gfx_demo#3]
It looks like something is wrong in the driver ssd1306_i2c.hpp.
When I run the demo, I only see 8 rows. The other rows are not written to: a former image is still there (I uploaded an image from another stack to be sure that the device was not faulty). Because the image in the 8 rows is so frantic, I tend to believe that the whole display is written in this "page". The position of these 8 rows is changing with every compilation. It looks like an initialization issue, but I cannot find it. I hope this description helps to find the culprit.
![SSD1306Demo](https://user-images.githubusercontent.com/24509794/146756882-fad3fe06-5187-4ec9-b658-4f5210ae1cd9.jpg)

**Comment by codewitch-honey-crisis** [comment]
I can tell from here your screen is broken. Maybe try this with one that isn’t. If it’s changing every compilation it’s *not* my code. Sent from Mail for Windows From: rolanddemeesterSent: Monday, December 20, 2021 2:59 AMTo: codewitch-honey-crisis/gfx_demoCc: SubscribedSubject: [codewitch-honey-crisis/gfx_demo] ssd1306_ic2 demo shows only 8 rows (Issue #3) It looks like something is wrong in the driver ssd1306_i2c.hpp.When I run the demo, I only see 8 rows. The other rows are not written to: a former image is still there (I uploaded an image from another stack to be sure that the device was not faulty). Because the image in the 8 rows is so frantic, I tend to believe that the whole display is written in this "page". The position of these 8 rows is changing with every compilation. It looks like an initialization issue, but I cannot find it. I hope this description helps to find the culprit.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by rolanddemeester** [comment]
OK, I ordered a few other modules. I will come back when I will have made the tests.

I will be very surprised if these would work: my current SSD1306 module works flawlessly with the u8g2 stack (see photo).

Kind regards.

**Comment by codewitch-honey-crisis** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by rolanddemeester** [comment]
Hello

Forget about this item: the three modules I tested are OK. So, probably the module I bought some years ago is faulty (timings?).

I propose to delete the issue I reported in git: it’s only noise.

Have an exciting 2022!

Roland De Meester

**Comment by codewitch-honey-crisis** [comment]
Thanks for letting me know!

**Comment by rolanddemeester** [comment]
Hello,

 

I found the display module based on SSD1306 a bit too small, I prefer the 1.3” one. Unfortunately, this module is based on SSH1106.

So I “adapted” your SSD1306 I2C driver to the SSH1106, with the help of its datasheet and some code I found on the web.

The demo runs without any problems, except that at the end of the moving sprite procedure some artifacts from the bitmaps from the former scene become visible at the left of the screen.

I suppose it has to be related to the way the bytes are written to the display, which is the major difference between the SSD1306 and the SSH1106. Therefor I changed one line in de demo: I don’t only clear the lcd but I draw a black bitmap to it, which clears the buffer as well.

I herewith send you the driver, it may or may not useful to you.

Regards, 

Roland De Meester

**Comment by codewitch-honey-crisis** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by rolanddemeester** [comment]
Hello

 

I struggled a bit to get the SSD1306 SPI demo running.

I found that some pieces were missing in the driver:

The non SPI related GPIO pins DC and RST are not set as output and stay low,
I added the code in the initialize_impl()

 

            //Initialize non-SPI GPIOs

            if(ESP_OK!=gpio_set_direction(PinDC, GPIO_MODE_OUTPUT)){

                return result::io_error;

            }

            if(ESP_OK!=gpio_set_direction(PinRst, GPIO_MODE_OUTPUT)){

                return result::io_error;

            }

 

I changed some code in the same method : you must call reset_impl() instead
of reset() because this causes a race condition.

I made sure that the reset pin is put high, even when no reset_before_init
is asked.

 

            if(reset_before_init) {

                r=reset_impl();

                if(result::success!=r && result::not_supported!=r) {

                    return r;

                }

            } 

            else {

                    //make sure the reset pin is high (non-active)

                    if(ESP_OK!= gpio_set_level(PinRst,1)){

                        return result::io_error;              

                    }

            }

 

A minor detail: a stray i2C statement (i2c_master_command mc) in the method
display_update.

 

Greetings,

Roland De Meester
